services:
  stunnel_server:
    image: ghcr.io/0xf00f00/stunnel:latest
    container_name: stunnel_server
    restart: unless-stopped
    volumes:
      - .:/etc/stunnel:ro
    network_mode: host
    dns:
      - 1.1.1.1
      - 1.0.0.1
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"